In [1]:
import torch

In [2]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
import src.models.submodules as S

In [4]:
conv = S.Conv(10, 10, 4, 1)
conv

Conv(
  (conv): Conv2d(10, 10, kernel_size=(4, 4), stride=(1, 1), padding=(1.5, 1.5))
  (batchNorm2d): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

In [5]:
rb = S.ResidualBlock(2, 2)
rb

ResidualBlock(
  (convLow1): Conv(
    (conv): Conv2d(2, 1, kernel_size=(1, 1), stride=(1, 1))
    (batchNorm2d): BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (convLow2): Conv(
    (conv): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1.0, 1.0))
    (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (convLow3): Conv(
    (conv): Conv2d(1, 2, kernel_size=(1, 1), stride=(1, 1))
    (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (convUp): Conv(
    (conv): Conv2d(2, 2, kernel_size=(1, 1), stride=(1, 1))
    (batchNorm2d): BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
)

In [6]:
hg = S.HourglassBlock(2, 2, 2)
hg

HourglassBlock(
  (residualBlock): ModuleDict(
    (2): ModuleDict(
      (up): ModuleDict(
        (0): ResidualBlock(
          (convLow1): Conv(
            (conv): Conv2d(2, 1, kernel_size=(1, 1), stride=(1, 1))
            (batchNorm2d): BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (convLow2): Conv(
            (conv): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1.0, 1.0))
            (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (convLow3): Conv(
            (conv): Conv2d(1, 2, kernel_size=(1, 1), stride=(1, 1))
            (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (convUp): Conv(
            (conv): Conv2d(2, 2, kernel_size=(1, 1), stride=(1, 1))
            (batchNorm2d): BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
      

In [10]:
hgAfter = S.HourglassAfter(2, 2, 2)
hgAfter

HourglassAfter(
  (residualBlock): ModuleDict(
    (0): ResidualBlock(
      (convLow1): Conv(
        (conv): Conv2d(2, 1, kernel_size=(1, 1), stride=(1, 1))
        (batchNorm2d): BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (convLow2): Conv(
        (conv): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1.0, 1.0))
        (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (convLow3): Conv(
        (conv): Conv2d(1, 2, kernel_size=(1, 1), stride=(1, 1))
        (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (convUp): Conv(
        (conv): Conv2d(2, 2, kernel_size=(1, 1), stride=(1, 1))
        (batchNorm2d): BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): ResidualBlock(
      (convLow1): Conv(
        (conv): Conv2d(2, 1, kernel_size=(1, 1), stride=(1, 1))
 

In [8]:
calLandmarks = S.CalLandmarks()
calLandmarks

CalLandmarks()

In [11]:
import src.models.elg as E

In [12]:
elg = E.ELG()
elg

ELG(
  (convPre): Conv(
    (conv): Conv2d(1, 32, kernel_size=(7, 7), stride=(1, 1), padding=(3.0, 3.0))
    (batchNorm2d): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (residualBlockPre1): ResidualBlock(
    (convLow1): Conv(
      (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
      (batchNorm2d): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (convLow2): Conv(
      (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1.0, 1.0))
      (batchNorm2d): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (convLow3): Conv(
      (conv): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1))
      (batchNorm2d): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (convUp): Conv(
      (conv): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1))
      (batchNorm2d): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=Tru

In [9]:
import torch
t = torch.randn(size=(32, 18, 2))
t

tensor([[[-0.8025, -1.0166],
         [-1.3170,  0.5870],
         [-0.4935,  0.0798],
         ...,
         [ 0.0830, -1.3237],
         [ 2.0345, -1.4770],
         [-0.6999, -1.2502]],

        [[-0.2400,  0.4120],
         [ 0.1771,  0.2020],
         [ 0.4769, -0.2480],
         ...,
         [ 1.0028,  2.1266],
         [-0.3760, -0.5145],
         [-1.3275, -0.1097]],

        [[-0.6953,  0.6919],
         [ 1.5187,  1.5821],
         [ 0.0254,  0.2705],
         ...,
         [ 1.1716, -0.7084],
         [ 2.3543,  0.3392],
         [ 1.4319, -0.6976]],

        ...,

        [[ 0.0432, -1.2215],
         [ 1.0668,  1.7338],
         [ 0.1829,  0.2136],
         ...,
         [ 1.5355,  0.2306],
         [-0.0315, -0.2774],
         [-0.8228, -0.1470]],

        [[-1.1234, -1.0910],
         [-1.1491,  1.2715],
         [-1.2245, -0.7319],
         ...,
         [ 1.9565, -0.0873],
         [ 0.6084,  2.1927],
         [-0.5168, -1.7524]],

        [[-0.4148, -0.0734],
       

In [34]:
torch.transpose(t, 1, 2)

tensor([[[ 0.8992,  0.5720, -0.8831,  ...,  0.6891, -0.3981, -0.4941],
         [ 0.9966,  1.6570, -0.0500,  ...,  0.7294,  0.9790, -0.8864]],

        [[-0.7335, -0.4766,  0.7941,  ..., -0.1512,  0.3336, -0.3897],
         [ 1.0111, -1.9817,  0.4900,  ..., -0.4471, -1.0809, -1.0333]],

        [[ 0.5992, -1.3514,  0.4614,  ...,  0.3282, -0.1646, -0.7101],
         [ 1.1017, -2.1903, -0.2068,  ..., -2.4828, -0.3858, -0.1849]],

        ...,

        [[ 0.3373, -1.3665,  1.5839,  ...,  0.3606, -1.0577,  0.2084],
         [-0.1785,  0.0519,  0.2111,  ...,  0.1438,  0.2427,  1.7416]],

        [[-0.2611, -0.8860, -0.9782,  ...,  0.2078,  1.8289, -0.8996],
         [ 0.8594,  0.8987, -0.1501,  ...,  0.3225, -0.8829,  0.8196]],

        [[-0.2177, -1.1429,  0.9535,  ..., -0.5549, -1.2321, -1.0991],
         [-0.7279, -0.9450,  0.3083,  ...,  1.7004, -0.5987,  0.9312]]])

In [7]:
import torch
a = torch.randn(size=(5, 5))
b = torch.randn(size=(5, 5))

In [8]:
a

tensor([[-1.3280e-03,  1.7322e-01, -6.6297e-01, -3.0830e-01,  2.9944e-01],
        [ 9.9380e-01,  4.2210e-01,  9.2541e-02, -1.5960e+00, -7.7134e-01],
        [ 2.0320e-01, -2.0889e-01,  4.6965e-01, -2.2855e+00, -1.0846e+00],
        [ 8.3128e-01,  1.6904e-01, -1.2506e-01, -3.0522e+00,  1.6573e+00],
        [ 4.4864e-02,  9.8693e-02, -1.0631e+00,  1.6853e+00, -1.0609e+00]])

In [9]:
b

tensor([[ 1.8824e+00,  1.3477e+00, -5.7018e-01,  9.5206e-01,  6.1180e-02],
        [-5.9295e-02, -4.6358e-01,  1.8478e+00, -2.2582e+00,  3.9496e-01],
        [ 1.6356e+00,  5.7438e-01,  1.3025e+00, -2.4912e+00, -1.1806e-01],
        [-3.7556e-01,  2.3273e-01,  8.8415e-01, -1.7300e-01, -1.2726e-03],
        [-5.2284e-01,  1.4934e+00,  9.2014e-01,  9.2565e-01, -8.7580e-01]])

In [10]:
a*b

tensor([[-2.4998e-03,  2.3345e-01,  3.7801e-01, -2.9352e-01,  1.8320e-02],
        [-5.8927e-02, -1.9568e-01,  1.7099e-01,  3.6042e+00, -3.0465e-01],
        [ 3.3235e-01, -1.1998e-01,  6.1173e-01,  5.6934e+00,  1.2805e-01],
        [-3.1220e-01,  3.9342e-02, -1.1057e-01,  5.2803e-01, -2.1091e-03],
        [-2.3456e-02,  1.4739e-01, -9.7822e-01,  1.5600e+00,  9.2916e-01]])

In [11]:
torch.square(a)

tensor([[1.7636e-06, 3.0005e-02, 4.3952e-01, 9.5052e-02, 8.9665e-02],
        [9.8763e-01, 1.7817e-01, 8.5638e-03, 2.5473e+00, 5.9497e-01],
        [4.1289e-02, 4.3636e-02, 2.2058e-01, 5.2233e+00, 1.1764e+00],
        [6.9103e-01, 2.8575e-02, 1.5640e-02, 9.3158e+00, 2.7465e+00],
        [2.0127e-03, 9.7403e-03, 1.1302e+00, 2.8402e+00, 1.1256e+00]])

In [52]:
import math
def compute_angular_loss(predict, label):
    """Pytorch method to calculate angular loss (via cosine similarity)"""
    def angle_to_unit_vectors(y):
        sin = torch.sin(y)
        cos = torch.cos(y)
        return torch.stack([
            cos[:, 0] * sin[:, 1],
            sin[:, 0],
            cos[:, 0] * cos[:, 1],
        ], dim=1)

    a = angle_to_unit_vectors(predict)
    b = angle_to_unit_vectors(label)
    ab = torch.sum(a*b, dim=1)
    a_norm = torch.sqrt(torch.sum(torch.square(a), dim=1))
    b_norm = torch.sqrt(torch.sum(torch.square(b), dim=1))
    cos_sim = ab / (a_norm * b_norm)
    cos_sim = torch.clip(cos_sim, -1.0 + 1e-6, 1.0 - 1e-6)
    ang = torch.acos(cos_sim) * 180. / math.pi
    return torch.mean(ang)

In [53]:
dtype = torch.float
device = torch.device("cpu")
a = torch.randn(size=(32, 2), device=device, dtype=dtype, requires_grad=True)
b = torch.randn(size=(32, 2), device=device, dtype=dtype, requires_grad=True)
loss = compute_angular_loss(a, b)

In [54]:
loss.backward()

In [55]:
a.grad

tensor([[-0.2074, -1.2663],
        [ 1.5925,  0.2117],
        [ 1.7191, -0.4893],
        [ 0.9966,  0.9156],
        [-1.3257, -0.4265],
        [ 0.3214, -0.7308],
        [-1.5927, -0.4712],
        [-1.7903,  0.0243],
        [ 0.6189, -1.3003],
        [ 1.1563,  1.3630],
        [-0.5421,  1.7005],
        [ 0.8738,  0.8870],
        [-1.5745, -0.3300],
        [-1.7904, -0.0149],
        [-0.8224, -1.5819],
        [ 1.7647, -0.3013],
        [-1.7584,  0.2876],
        [ 1.7842,  0.0672],
        [ 1.6497, -0.6783],
        [-1.7783,  0.1147],
        [ 1.7859, -0.0703],
        [ 1.7893, -0.0455],
        [ 1.7317, -0.4313],
        [-1.1127,  1.0271],
        [ 0.3122,  1.7144],
        [-1.5572,  0.3834],
        [-1.7565, -0.1555],
        [-1.1138,  1.3919],
        [ 1.7282, -0.2478],
        [-1.6566,  0.1587],
        [ 0.3920,  1.3703],
        [-0.8542, -0.7350]])

In [44]:
def compute_coord_loss(predict, label):
    loss = torch.nn.MSELoss()(predict, label)
    return loss

In [48]:
dtype = torch.float
device = torch.device("cpu")
a = torch.randn(size=(32, 18, 2), device=device, dtype=dtype, requires_grad=True)
b = torch.randn(size=(32, 18, 2), device=device, dtype=dtype, requires_grad=True)
loss = compute_coord_loss(a, b)

In [49]:
loss

tensor(2.1000, grad_fn=<MseLossBackward>)

In [50]:
loss.backward()

In [51]:
a.grad

tensor([[[ 4.7074e-03, -1.9146e-03],
         [ 9.7514e-04, -1.9047e-03],
         [-2.5062e-03,  2.9323e-03],
         ...,
         [-3.0041e-03,  1.2131e-03],
         [-1.1349e-03, -2.2386e-04],
         [ 1.4278e-04, -2.9723e-03]],

        [[-1.2512e-03, -1.0431e-03],
         [-8.0369e-05, -5.8350e-04],
         [-3.0877e-03,  7.2709e-04],
         ...,
         [ 3.3036e-03, -2.1611e-03],
         [ 1.7574e-03,  3.1217e-04],
         [-7.5153e-04, -2.3203e-04]],

        [[ 1.9867e-03, -3.9162e-03],
         [ 2.9016e-03, -2.2006e-03],
         [ 1.5028e-03, -1.7555e-03],
         ...,
         [-4.8453e-04, -5.5053e-04],
         [ 8.1248e-04,  4.2297e-03],
         [ 1.9523e-03,  4.4047e-03]],

        ...,

        [[-1.9830e-03, -1.0014e-06],
         [ 8.9070e-04,  1.4197e-03],
         [-2.9995e-03,  5.8961e-04],
         ...,
         [ 1.5645e-03, -1.0544e-03],
         [-1.7116e-03, -6.1940e-03],
         [-6.9520e-04,  2.5292e-03]],

        [[-2.2285e-03,  1.7747e-03