In [5]:
import torch
import numpy as np

In [2]:
ldmks = torch.randn(2, 8, 2).cuda()
ldmks

tensor([[[-0.3311,  0.3914],
         [-0.6793,  1.1581],
         [-0.3154,  0.5366],
         [-0.0642,  1.6867],
         [ 0.3482,  0.6087],
         [ 0.5800, -0.5502],
         [-1.1955, -0.8860],
         [-0.3274,  2.0680]],

        [[ 0.9161,  1.1640],
         [ 0.9055, -0.9205],
         [-0.4583,  0.9977],
         [ 0.7823, -0.1852],
         [-0.0817, -2.2772],
         [-0.8077, -0.7288],
         [ 0.7142,  1.2565],
         [ 0.1752, -1.1366]]], device='cuda:0')

In [4]:
for e in range(len(ldmks)):
    eye_width = torch.sqrt(torch.mean(torch.square(ldmks[e][0] - ldmks[e][4])))
    ldmks[e] = ldmks[e] / eye_width
    gaze_prior = ldmks[e][-2] - ldmks[e][-1]
    ldmks[e][-2] = gaze_prior
ldmks

tensor([[[-0.6566,  0.7762],
         [-1.3470,  2.2965],
         [-0.6254,  1.0640],
         [-0.1272,  3.3448],
         [ 0.6904,  1.2070],
         [ 1.1501, -1.0910],
         [-1.7215, -5.8578],
         [-0.6492,  4.1009]],

        [[ 0.3616,  0.4594],
         [ 0.3574, -0.3633],
         [-0.1809,  0.3938],
         [ 0.3088, -0.0731],
         [-0.0323, -0.8988],
         [-0.3188, -0.2877],
         [ 0.2127,  0.9446],
         [ 0.0692, -0.4486]]], device='cuda:0')

In [1]:
def vector_to_pitchyaw(vectors):
    r"""Convert given gaze vectors to yaw (:math:`\theta`) and pitch (:math:`\phi`) angles.

    Args:
        vectors (:obj:`numpy.array`): gaze vectors in 3D :math:`(n\times 3)`.

    Returns:
        :obj:`numpy.array` of shape :math:`(n\times 2)` with values in radians.
    """
    n = vectors.shape[0]
    out = np.empty((n, 2))
    # 将向量标准化
    vectors = np.divide(vectors, np.linalg.norm(vectors, axis=1).reshape(n, 1))
    out[:, 0] = np.arcsin(vectors[:, 1])  # phi
    out[:, 1] = np.arctan2(vectors[:, 0], vectors[:, 2])  # theta
    return out

In [24]:
a = [-0.6073, 0.2457, -0.7555]
a[0] = -a[0]
a = np.expand_dims(np.array(a), axis=0)
a

array([[ 0.6073,  0.2457, -0.7555]])

In [25]:
vector_to_pitchyaw(a)

array([[0.24824658, 2.46451553]])

In [28]:
np.arctan2(0.6073, -0.7555)

2.4645155305260342

In [29]:
np.arctan(0.6073 / -0.7555)

-0.6770771230637591